name: Run tests and generate coverage in Pull Requests

on: [ pull_request ]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2